version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres_db_service
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./Backend/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  nodejs:
    build: ./Backend   
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      PGHOST: ${PGHOST}
      PGPORT: 5432
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  frontend:
    build: ./frontend
    container_name: react_app
    ports:
      - "80:80"
    depends_on:
      - nodejs
    volumes:
     - ./frontend/build:/usr/share/nginx/html

volumes:
  pgdata:
